using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;

namespace SteeringBehaviours
{

    public class AIAgent : MonoBehaviour
    {
        public float maxSpeed = 10f;
        public float maxDistance = 5f;
        public bool updatePosition = true;
        public bool updateRotation = true;
        public Vector3 velocity;
       
        private Vector3 force;
        private List<SteeringBehaviour> behaviours;
        private NavMeshAgent agent;

        private void Awake()
        {
            behaviours = GetComponents<SteeringBehaviour>();
            agent = GetComponent<NavMeshAgent>();
        }
        // Update is called once per frame
        void Update()
        {
            ComputeForces();
            ApplyVelocity();

            /* if there is a point set
            if(point.magnitude > 0)
            {
                // set the agent's destination to that point
                agent.SetDestination(point);
            } 
           */ 
        }
        // Calculate all the forces generated by each attached SteeringBehaviour
        private void ComputeForces()
        {
            // Reset velocity
            velocity = Vector3.zero;
            // Loop through each behaviour
            for(int i = 0; i < behaviours.Length; i++)
            {
                // Get force from behaviour
                Vector3 force = behaviours[i].GetForce();
                // Add it to velocity
                velocity += force;
            }
        }
        // Apply the total velocity to the AIAgent
        private void ApplyVelocity()
        {
            // Get an offset position as new target
            Vector3 point = transform.position + velocity * Time.deltaTime;
            // Apply velocity to transform
            agent.SetDestination(point);
        }
        /* public void SetTarget(Vector3 point)
        {
            this.point = point; // sometimes you actually NEED to use "this." in order to clarify which variable belongs
        } */
    }
}
